Amber_planning_group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - Rev2
    - Rev3
    - Rev6
    - Rev7
    - Rev9
    - Rev10
    - Rev12
  gains:
    Rev2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev9:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev10:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev12:
      p: 100
      d: 1
      i: 1
      i_clamp: 1